### ISSUE TITLE
[Progress Tracker] A Unified Scenario Data Format

### ISSUE THREAD

**Issue by QuanyiLi** [metadriverse/metadrive#353]
Updates for WaymoEnv:
- [x] Convert to new data format
- [x] Load new format data to MetaDrive
- [x] Replace 3 MetaDrive internal example cases
- [ ] Fix interpolating line: **Add test**
- [x] Waymo map store map when reset
- [x] Waymo car type randomization
- [x] upgrade sidewalk
- [x] traffic light
- [x] Remove static car option
- [x] Remove protobuf dependency
- [x] Make replay policy for replay mode
- [x] IDM policy for IDM mode
- [x] WaymoTraffic after step create!
- [x] waymo_data_directory->data_directory
- [x] Lane Polygon support
- [ ] Lateral Distance observation
- [x] set_angular_velocity

**TODO for exporting/loading scenario:**
- [x] rename ```case``` -> ```scenario``` for all API
- [x] make scenario loader. Though the exported scenarios can be loaded by WaymoEnv, it is just a workaround.
- [x] exporting TrafficLight
- [x] exporting/loading objects
- [x] exporting/loading pedestrians
- [x] exporting/loading cyclist 
- [x] Create from Lane Polygon

**Comment by pengzhenghao** [comment]
This floor discusses the issue about data alignment:

* [ ] Revisit Nuplan & Waymo dataset, understand how they align other modalities with the "meta data". We need to remain the "time stamp" in MetaDrive Format (MDF).
* [ ] Transform the "version" to a native Python datetime compatible data, so that we compare data version directly!
